---
# tasks file for tomcat85
# - filesystem
# - users(individuals, group, tomcat)
# - install java
# - unarchive tomcat from files
# - configure tomcat(server.xml, catalina ... )
# - configure bashes
# - make test app
# - start tomcat
# - Undo installation
#
- name: Extract Tomcat archive
  unarchive:
    src: apache-tomcat-8.5.43.tar.gz
    dest: "{{ tomcat.home }}"
- name: Configure Tomcat .bash_profile
  file:
    src: .bash_profile.j2
    dest: "{{ tomcat.home }}/.bash_profile" 
- name: Configure Tomcat server.xml
  template:
    src: server.xml.j2
    dest: "{{ tomcat.con1.home }}/conf/server.xml"
#- name: Make test application
#- name: Configure permissions
#- name: Start Tomcat
