---
# tasks file for tomcat85
# - make test app
# - start tomcat
# - Undo installation
#
- name: Ensure given version of Openjdk is installed
  package:
    name: "{{ java_version }}"
    state: present
- name: Configure Tomcat admin .bash_profile
  template:
    src: .bash_profile.j2
    dest: "{{ tomcat_install_home }}/.bash_profile"
- name: Setup Tomcat home
  file:
    path: "{{ tomcat_home }}"
    state: directory
    mode: 0750
    owner: "{{ tomcat_admin_username }}"
    group: "{{ tomcat_admin_group }}"
- name: Setup Tomcat Container1
  import_tasks: con1.yml
- name: Setup Tomcat Container2
  import_tasks: con2.yml
#- name: Setup Tomcat Cluster
#- name: Make test application
#- name: Configure permissions
#- name: Start Tomcat
